#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
STOP=50

USE_PROCD=1
PROG=/usr/sbin/lighttpd

validate_conf() {
	$PROG -tt -f /etc/lighttpd-public/lighttpd.conf >/dev/null || {
		echo 1>&2 "lighttpd.conf validation failed"
		return 1
}
}

start_service() {
	user_exists http || user_add http
	for i in /var/log/lighttpd-public /var/lib/lighttpd-public /var/cache/lighttpd-public; do
		[ -d "$i" ] || {
			mkdir -m 0775 -p "$i"
			chgrp www-data "$i"
		}
	done

	validate_conf || exit 1

	procd_open_instance lighttpd-public
	procd_set_param command $PROG -D -f /etc/lighttpd-public/lighttpd.conf
	procd_close_instance
}

service_triggers() {
#	procd_add_reload_interface_trigger loopback
#	procd_add_reload_interface_trigger lan
	procd_add_reload_interface_trigger eth2
}

reload_service() {
	validate_conf || exit 1
	# lighttpd graceful restart (SIGUSR1)
	procd_send_signal lighttpd-public '*' USR1
}

relog() {
	# lighttpd reopen log files (SIGHUP)
	procd_send_signal lighttpd-public '*' HUP
}

EXTRA_COMMANDS="relog"
EXTRA_HELP="	relog   Reopen log files (without reloading)"
